const express = require('express')
const path = require('path')
const cookieParser = require('cookie-parser')
const logger = require('morgan')
const cors = require('cors')
const mongoose = require('mongoose')
const dotenv = require('dotenv')
const { authenMiddleware, authorizeMiddleware } = require('./helpers/auth')
const { ROLE } = require('./constant')

const indexRouter = require('./routes/index')
const usersRouter = require('./routes/users')
const authRouter = require('./routes/auth')
const uploadRouter = require('./routes/upload')
const profileRouter = require('./routes/profile')
const requestRouter = require('./routes/request')
const booksRouter = require('./routes/books')
const confirmPasswordRouter = require('./routes/confirmPassword')
const checkRoles = require('./routes/checkRoles')
const checkRequestRoles = require('./routes/checkRequestRoles')
const wishList = require('./routes/wishlist')
const cart = require('./routes/cart')
const checkout = require('./routes/checkout')
const inventory = require('./routes/inventoryUser')
const checkBook = require('./routes/checkHaveBook')
const checkDuplicateUser = require('./routes/checkDuplicateUser')
const bestsellerRouter = require('./routes/bestseller')
const newEntryRouter = require('./routes/newentry')
const ratingRouter = require('./routes/rating')
const receiptRouter = require('./routes/receipt')
const ratingUserBooks = require('./routes/ratingUserBooks')
const recommendedRouter = require('./routes/recommended')
const halloffameRouter = require('./routes/halloffame')
const getRatingBookRouter = require('./routes/getRatingBook')
const searchBookRouter = require('./routes/searchBook')
const receiptBookRouter = require('./routes/receiptBooks')
const AllReviewRouter = require('./routes/allReviewBooks')
const requestCoinRouter = require('./routes/requsetCoin')
const requestHistoryAdmin = require('./routes/requestHistoryAdmin')
const checkDuplicateBook = require('./routes/checkDuplicateBook')
const allRequestRouter = require('./routes/allRequest')
const notificationsRouter = require('./routes/notifications')
const promptpayRouter = require('./routes/promptpay')
const historyCRUDRouter = require('./routes/crudHistoryAdmin')
const historyCRUDBookRouter = require('./routes/crudHistoryBook')
const userDeletedRouter = require('./routes/userDeleted')
const bookDeletedRouter = require('./routes/booksDeleted')
const totalSoldRouter = require('./routes/totalSold')
const findUserRouter = require('./routes/findRoleUser')
const allRatingBooksRouter = require('./routes/allRatingBooks')
const requestBookRouter = require('./routes/requestBooks')
const BookSellRouter = require('./routes/usersellbook')

mongoose.set('strictQuery', false)
dotenv.config()
mongoose.connect('mongodb://localhost:27017/Project_intern')
const app = express()

app.use(cors())
app.use(logger('dev'))
app.use(express.json())
app.use(express.urlencoded({ extended: true }))
app.use(cookieParser())
app.use(express.static(path.join(__dirname, 'public')))

app.use('/', indexRouter)
app.use('/users', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN, ROLE.SELL]), usersRouter)
app.use('/auth', authRouter)
app.use('/upload', express.static('/uploads'), authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN, ROLE.USER, ROLE.SELL]), uploadRouter)
app.get('/uploads/:filename', (req, res) => {
  const options = {
    root: path.join(__dirname, 'uploads'),
    headers: {
      'x-timestamp': Date.now(),
      'x-sent': true
    }
  }
  const fileName = req.params.filename
  res.sendFile(fileName, options, (err) => {
    if (err) {
      console.log(err)
    } else {
      console.log('Sent:', fileName)
    }
  })
}, authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN, ROLE.USER, ROLE.SELL]))
app.use('/profile', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN, ROLE.USER, ROLE.SELL]), profileRouter)
app.use('/request', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN, ROLE.USER, ROLE.SELL]), requestRouter)
app.use('/books', booksRouter)
app.use('/confirmPassword', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN, ROLE.USER, ROLE.SELL]), confirmPasswordRouter)
app.use('/checkRoles', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN, ROLE.USER, ROLE.SELL]), checkRoles)
app.use('/checkRequestRoles', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN, ROLE.USER, ROLE.SELL]), checkRequestRoles)
app.use('/wishlist', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN, ROLE.USER, ROLE.SELL]), wishList)
app.use('/cart', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN, ROLE.USER, ROLE.SELL]), cart)
app.use('/checkout', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN, ROLE.USER, ROLE.SELL]), checkout)
app.use('/inventory', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN, ROLE.USER, ROLE.SELL]), inventory)
app.use('/checkBook', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN, ROLE.USER, ROLE.SELL]), checkBook)
app.use('/checkDuplicateUser', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN]), checkDuplicateUser)
app.use('/bestseller', bestsellerRouter)
app.use('/newentry', newEntryRouter)
app.use('/rating', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN, ROLE.USER, ROLE.SELL]), ratingRouter)
app.use('/receipt', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN, ROLE.USER, ROLE.SELL]), receiptRouter)
app.use('/ratingUserBooks', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN, ROLE.USER, ROLE.SELL]), ratingUserBooks)
app.use('/recommended', recommendedRouter)
app.use('/halloffame', halloffameRouter)
app.use('/ratingBook', getRatingBookRouter)
app.use('/searchbook', searchBookRouter)
app.use('/receiptbook', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN, ROLE.USER, ROLE.SELL]), receiptBookRouter)
app.use('/allreview', AllReviewRouter)
app.use('/requestcoin', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN, ROLE.USER, ROLE.SELL]), requestCoinRouter)
app.use('/history', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN]), requestHistoryAdmin)
app.use('/checkDuplicateBook', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN]), checkDuplicateBook)
app.use('/allrequest', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN, ROLE.USER, ROLE.SELL]), allRequestRouter)
app.use('/notifications', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN, ROLE.USER, ROLE.SELL]), notificationsRouter)
app.use('/generateQR', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN, ROLE.USER, ROLE.SELL]), promptpayRouter)
app.use('/historycrud', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN]), historyCRUDRouter)
app.use('/userdelete', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN]), userDeletedRouter)
app.use('/historycrudbook', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN]), historyCRUDBookRouter)
app.use('/bookdelete', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN]), bookDeletedRouter)
app.use('/totalsold', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN]), totalSoldRouter)
app.use('/finduser', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN]), findUserRouter)
app.use('/allrating', allRatingBooksRouter)
app.use('/requestbook', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN, ROLE.USER, ROLE.SELL]), requestBookRouter)
app.use('/booksell', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN, ROLE.USER, ROLE.SELL]), BookSellRouter)

module.exports = app
